backend:
  name: github
  repo: mateuszmatyszkowicz/xsolve-tech
  branch: feature/netlify-cms


media_folder: static/img
public_folder: /img

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "General Settings"
        file: "meta/config.json"
        description: "General Site Settings"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string", required: false}
          - {label: "Alternative Site Title (short)", name: "siteTitleAlt", widget: "string", required: false}
          - {label: "Site Description", name: "siteDescription", widget: "string", required: false}
          - {label: "Default Site Cover", name: "siteCover", widget: "image", required: false}
  - name: "blog"
    label: "Blog Articles"
    label_singular: "Blog Article"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-page"}
      - {label: "Title", name: "title", widget: "string", pattern: ['.{5,}', "Must have at least 5 characters"]}
      - {label: "Lead Content", name: "lead", widget: "markdown", required: false}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Article Tags", name: "tags", widget: "list"}


